### ISSUE TITLE
Change icon from inner_node_icon to outer_node_icon on fold inner node.

### ISSUE THREAD

**Issue by encode-this** [ElPiloto/sidekick.nvim#4]
Make sure to add opposite behavior, outer back to inner on unfold.

**Comment by ElPiloto** [comment]
Closed via https://github.com/ElPiloto/sidekick.nvim/commit/855ec91cbe49f98271fe499aafd7ef6f77221345 which adds `g:sidekick_outer_node_folded_icon` for specifying custom node on fold.
